apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 940168446867.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 940168446867.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: 940168446867.dkr.ecr.ap-southeast-2.amazonaws.com/demo-frontend
  newName: 940168446867.dkr.ecr.ap-southeast-2.amazonaws.com/demo-frontend
  newTag: 71be74bc
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
